### PR TITLE
Fixed handling IEnumerable by DictionaryStringObjectJsonConverter

### LINKED ISSUE #438: TargetParameterCountException thrown by DictionaryStringObjectJsonConverter.CustomWrite()
### Stacktrace

```log: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at JWT.Serializers.Converters.DictionaryStringObjectJsonConverterCustomWrite.<>c__DisplayClass2_0.<HandleValue>b__1(PropertyInfo p) in MyProject/jwt/src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs:line 121
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at JWT.Serializers.Converters.DictionaryStringObjectJsonConverterCustomWrite.HandleValue(Utf8JsonWriter writer, String key, Object objectValue) in MyProject/jwt/src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs:line 119
   at JWT.Serializers.Converters.DictionaryStringObjectJsonConverterCustomWrite.Write(Utf8JsonWriter writer, Dictionary`2 value, JsonSerializerOptions options) in MyProject/jwt/src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs:line 45
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at JWT.Serializers.SystemTextSerializer.Serialize(Object obj) in MyProject/jwt/src/JWT/Serializers/SystemTextSerializer.cs:line 28
   at JWT.JwtEncoder.Encode(IDictionary`2 extraHeaders, Object payload, Byte[] key) in MyProject/jwt/src/JWT/JwtEncoder.cs:line 66
   at JWT.Builder.JwtBuilder.Encode() in MyProject/jwt/src/JWT/Builder/JwtBuilder.cs:line 263
   at WebSockets.Services.AuthService.CreateSession(User user) in MyProject/DirtyChat/Services/AuthService.cs:line 92
```

_Originally posted by @MaxLevs in https://github.com/jwt-dotnet/jwt/issues/436#issuecomment-1255363578_

### PR DESCRIPTION
**Pull request by hartmark**
Resolves #438.

### CODE REVIEW

File: src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs [hunk 1]
```diff
@@ -114,6 +114,16 @@ private static void HandleValue(Utf8JsonWriter writer, string key, object object
                     writer.WriteEndArray();
                     break;
                 }
+                case System.Collections.IEnumerable enumerable:
```
Comment (abatishchev) [inline src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs:117]: It doesn't support something like this:

```c#
case object[] arr:
case System.Collections.IEnumerable arr:
{
    // use arr
}
```
?

**Comment by abatishchev** [comment]
Awesome, thanks you both!

File: src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs (hunk 1 above)
Comment (abatishchev) [reply src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs:117]: If no, should we introduce a helper method called form both cases?

Comment (hartmark) [reply src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs:117]: It doesn't support something like this because the name list conflicts as it is created like a variable:
```
                case object[] list:
                case System.Collections.IEnumerable list:
                {
                    writer.WriteStartArray();
                    foreach (var item in list)
                    {
                        HandleValue(writer, item);
                    }
                    writer.WriteEndArray();
                    break;
                }
```

We can make a helper method instead.

Comment (abatishchev) [reply src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs]: Just a quick question: since Array implements IEnunerable, shouldn't having just IEnunerable handle both?

Comment (hartmark) [reply src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs]: Good point! I'll try after work.

Comment (hartmark) [reply src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs]: Sorry for late reply, but you're right! An array implements IEnumerable so I have pushed an even better fix :)

**Comment by hartmark** [comment]
Please re-review the fix @abatishchev

**Review by abatishchev — APPROVED** [review]
